variant: flatcar
version: 1.0.0
systemd:
  units:
    - name: installer.service
      enabled: true
      contents: |
        [Unit]
        Requires=network-online.target
        After=network-online.target
        [Service]
        Type=simple
        ExecStart=/opt/installer
        [Install]
        WantedBy=multi-user.target
    # Avoid using the standard SSH port so terraform apply cannot SSH until
    # post-install. But admins may SSH to debug disk install problems.
    # After install, sshd will use port 22 and users/terraform can connect.
    - name: sshd.socket
      dropins:
        - name: 10-sshd-port.conf
          contents: |
            [Socket]
            ListenStream=
            ListenStream=2222
storage:
  files:
    - path: /opt/installer
      mode: 0500
      contents:
        inline: |
          #!/bin/bash -ex
          curl --retry 10 "${ignition_endpoint}?mac=${mac}&os=installed" -o ignition.json
          flatcar-install \
            -d ${install_disk} \
            -C ${os_channel} \
            -V ${os_version} \
            ${baseurl_flag} \
            -i ignition.json
          udevadm settle
          efipartition=$(lsblk ${install_disk} -J -oLABEL,PATH  | jq -r '.blockdevices[] | select(.label == "EFI-SYSTEM")'.path)
          #efipartition=$(lsblk ${install_disk} -oLABEL,PATH | awk '$1 == "EFI-SYSTEM" {print $2}')
          mkdir /tmp/efipartition
          mount $${efipartition} /tmp/efipartition
          pushd /tmp/efipartition
            version=$(curl --silent "${matchbox_endpoint}/assets/uefi/latest-version")
            curl -LO ${matchbox_endpoint}/assets/uefi/RPi4_UEFI_Firmware_$${version}.zip
            unzip RPi4_UEFI_Firmware_$${version}.zip
            rm RPi4_UEFI_Firmware_$${version}.zip
          popd
          umount /tmp/efipartition
          udevadm settle
          systemctl reboot
passwd:
  users:
    - name: core
      ssh_authorized_keys:
        - "${ssh_authorized_key}"
